// HTML rendering for the readiness report.
//
// Design constraints: single self-contained file (inline CSS, zero external
// assets) so it can be opened from disk and saved via the browser's
// Print → Save as PDF. Visual identity is the open-source project only —
// no company branding, no logos, neutral grayscale styling.
package report

import (
	"fmt"
	"html/template"
	"strings"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Passwordless Readiness Report</title>
<style>
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #1a1a1a; max-width: 880px; margin: 0 auto; padding: 32px 24px 64px; line-height: 1.55; }
header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
header p { margin: 4px 0 0; color: #555; }
h1 { font-size: 28px; margin: 0; }
h2 { font-size: 19px; margin: 32px 0 12px; border-bottom: 1px solid #ddd; padding-bottom: 6px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; margin: 20px 0; }
.card { border: 1px solid #ddd; border-radius: 8px; padding: 14px; text-align: center; }
.card .n { font-size: 30px; font-weight: 700; }
.card .l { color: #555; font-size: 13px; }
.card.ready .n { color: #1a7a34; }
.card.remed .n { color: #b26a00; }
.card.exc .n { color: #555; }
.card.unk .n { color: #999; }
ul.items { list-style: none; padding: 0; margin: 0; }
ul.items li { border: 1px solid #e5e5e5; border-radius: 6px; padding: 10px 12px; margin-bottom: 8px; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e5e5; vertical-align: top; }
th { color: #555; font-weight: 600; }
code { background: #f4f4f4; padding: 1px 5px; border-radius: 4px; font-size: 13px; }
footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #555; font-size: 13px; }
.toolbar { margin: 0 0 20px; }
.toolbar button { font-size: 15px; padding: 9px 18px; border-radius: 6px;
  border: 1px solid #1a1a1a; background: #1a1a1a; color: #fff; cursor: pointer; }
.toolbar button:hover { background: #333; }
@media print {
  .toolbar { display: none; }
  body { padding: 0; max-width: none; }
  ul.items li, .card { break-inside: avoid; }
}
@page { margin: 18mm 15mm; }
</style>
</head>
<body>
<header>
<h1>Passwordless Readiness Report</h1>
<p>Generated by <a href="https://github.com/locke-inc/go-passwordless">go-passwordless</a>,
an open-source readiness assessment tool. Read-only; nothing in your environment was changed.</p>
</header>

<div class="toolbar"><button onclick="window.print()">Save as PDF / Print</button></div>

<div class="cards">
<div class="card ready"><div class="n">{{.Summary.ReadyNow}}</div><div class="l">Ready now</div></div>
<div class="card remed"><div class="n">{{.Summary.NeedsRemediation}}</div><div class="l">Need remediation</div></div>
<div class="card exc"><div class="n">{{.Summary.Exceptions}}</div><div class="l">Exceptions</div></div>
<div class="card unk"><div class="n">{{.Summary.Unknown}}</div><div class="l">Unknown</div></div>
</div>

{{range .Phases}}
<h2>{{.Name}}</h2>
{{if .Items}}<ul class="items">{{range .Items}}<li>{{.}}</li>{{end}}</ul>{{else}}<p>None.</p>{{end}}
{{end}}

{{if .Summary.Findings}}
<h2>Blockers</h2>
<table><tr><th>Category</th><th>Subject</th><th>Detail</th><th>Source</th></tr>
{{range .Summary.Findings}}<tr><td><code>{{.Category}}</code></td><td>{{.Subject}}</td><td>{{.Detail}}</td><td><code>{{.Source}}</code></td></tr>{{end}}
</table>
{{end}}

<h2>Cost of staying on passwords</h2>
{{if .Cost.Complete}}
<p>Estimated annual helpdesk cost of password resets: <strong>{{.CostFormatted}}</strong> (from your inputs).</p>
{{else}}
<p>Incomplete: provide resets/month, minutes/reset, and hourly rate to compute.</p>
{{end}}
{{if .Cost.ProvidedBreachEstimate}}<p>Your estimated breach exposure: <strong>{{.BreachFormatted}}</strong> (customer estimate, not tool data).</p>{{end}}

<h2>Next steps</h2>
<p>Work through the phases above in order. When you are ready to implement phishing-resistant
authentication, the open-source <a href="https://github.com/locke-inc/open-passkey">open-passkey</a>
libraries add WebAuthn/passkey support to any app.</p>

<footer>Report generated by <a href="https://github.com/locke-inc/go-passwordless">go-passwordless</a>
({{.SchemaVersion}}). Inventory and report stay on your machine.</footer>
</body>
</html>`

// htmlView is the template input: Report plus preformatted currency strings
// (currency formatting is presentation, so it lives here, not in cost).
type htmlView struct {
	Report
	CostFormatted   string
	BreachFormatted string
}

// ToHTML renders a self-contained, print-friendly report page.
func ToHTML(r Report) (string, error) {
	t, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return "", err
	}
	v := htmlView{Report: r}
	if r.Cost.Complete {
		v.CostFormatted = fmt.Sprintf("$%.2f", r.Cost.AnnualResetCost)
	}
	if r.Cost.ProvidedBreachEstimate > 0 {
		v.BreachFormatted = fmt.Sprintf("$%.2f", r.Cost.ProvidedBreachEstimate)
	}
	var b strings.Builder
	if err := t.Execute(&b, v); err != nil {
		return "", err
	}
	return b.String(), nil
}
